name: Deploy Java Web App - 1 

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: self-hosted

    steps:
    #- name: Set PowerShell Execution Policy
    #  run: Set-ExecutionPolicy Unrestricted -Scope Process
    
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
        
    - name: Build with Maven
      # run: mvn -B package --file pom.xml
      run: mvn clean install

    - name: Deploy to Tomcat
      #run: curl -u ${{ secrets.TOMCAT_USERNAME }}:${{ secrets.TOMCAT_PASSWORD }} --upload-file C:\actions-runner\_work\java-azure-devops-master-2\java-azure-devops-master-2\target\JSPSample-0.0.1.war http://localhost:8081/manager/text/deploy?path=/your-app
      run: curl -u robot:123 --upload-file C:\actions-runner\_work\java-azure-devops-master-2\java-azure-devops-master-2\target\JSPSample-0.0.1.war http://localhost:8081/manager/text/deploy?path=/your-app


      env:
        TOMCAT_USERNAME: ${{ secrets.TOMCAT_USERNAME }}
        TOMCAT_PASSWORD: ${{ secrets.TOMCAT_PASSWORD }}
